expose getters for reconcilers to get created endpoint and transport
konveyor/crane-lib pull request #48
Opened 2021-07-14 02:29 UTC by alaypatel07

2021-07-14 02:30 UTC, alaypatel07 commented on state_transfer/endpoint/route/route.go
> +	err := c.Get(context.TODO(), types.NamespacedName{Name: r.NamespacedName().Name, Namespace: r.NamespacedName().Namespace}, route)
s/context.TODO()/context.Background()/ for uniformity

2021-07-14 02:31 UTC, alaypatel07 commented on state_transfer/transport/stunnel/server.go
> +	return secret, err
needs to start wrapping errors

2021-07-14 02:31 UTC, alaypatel07 commented on state_transfer/transport/stunnel/stunnel.go
> +		fmt.Printf("transport: %s Client Config is not created", obj)
need to start thinking about loggers

2021-07-14 02:35 UTC, alaypatel07 commented
I need to and the getters for other packages, but wanted to throw the PR out there for initial feedbacl

2021-07-15 16:48 UTC, pranavgaikwad requested changes
Overall looks good to me. I'd ask for renaming `GetTransport()` method. The method name should imply that its constructing a Transport object by reconciling the observed state and not simply returning the Transport object from memory.

2021-07-15 19:29 UTC, shawn-hurley approved these changes

2021-07-16 15:04 UTC, pranavgaikwad approved these changes

2021-07-16 19:23 UTC, merged